### ISSUE TITLE
There is an error:   ERROR in ./src/js/app.js

### ISSUE THREAD

**Issue by whatifif** [ngokevin/a-udioworld#2]
ERROR in ./src/js/app.js
Module build failed: SyntaxError: /home/whatif/projects/react-webvr/a-wakens/src/js/app.js: A semicolon is required after a class property (82:3)
  80 |       this.audio.play();
  81 |     }, 50);

> 82 |   }
>      |    ^
>   83 | 
>   84 |   getAudio() {
>   85 |     return this.audio;
>     at Parser.pp.raise (/home/whatif/projects/react-webvr/a-wakens/node_modules/babylon/index.js:1425:13)
>     at Parser.pp.parseClassProperty (/home/whatif/projects/react-webvr/a-wakens/node_modules/babylon/index.js:2577:10)
>     at Parser.parseClassProperty (/home/whatif/projects/react-webvr/a-wakens/node_modules/babylon/index.js:3791:20)
>     at Parser.pp.parseClassBody (/home/whatif/projects/react-webvr/a-wakens/node_modules/babylon/index.js:2482:34)
>     at Parser.pp.parseClass (/home/whatif/projects/react-webvr/a-wakens/node_modules/babylon/index.js:2425:8)
>     at Parser.pp.parseStatement (/home/whatif/projects/react-webvr/a-wakens/node_modules/babylon/index.js:1889:19)
>     at Parser.parseStatement (/home/whatif/projects/react-webvr/a-wakens/node_modules/babylon/index.js:3580:22)
>     at Parser.pp.parseBlockBody (/home/whatif/projects/react-webvr/a-wakens/node_modules/babylon/index.js:2294:21)
>     at Parser.pp.parseTopLevel (/home/whatif/projects/react-webvr/a-wakens/node_modules/babylon/index.js:1823:8)
>     at Parser.parse (/home/whatif/projects/react-webvr/a-wakens/node_modules/babylon/index.js:1396:17)
>  @ multi main

**Comment by ngokevin** [comment]
Thanks!
